In [59]:
import numpy as np

### 1 

In [ ]:
#arrayin 1 ci elementinden [2] baslayaraq iki addimla elementleri secirik(even number), 
#kvadratini tapib array-e beraber edirik

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [73]:
arr=arr[1::2]
arr

array([ 2,  4,  6,  8, 10])

In [74]:
arr=arr*arr
arr

array([  4,  16,  36,  64, 100])

### 2


In [ ]:
#array-i eks terefden 1 adimla secirik

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [76]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 3

In [77]:
arr = np.array([100, 20, 32, 44, 59, 231, 5, 22, 93, 113, 16, 88])

In [78]:
arr.mean()

68.58333333333333

In [79]:
np.median(arr)

51.5

In [80]:
arr.max()

231

In [81]:
arr.min()

5

In [82]:
arr.var()

3640.4097222222226

### 4

In [83]:
import pandas as pd
import numpy as np

In [159]:
df=pd.read_csv('titles.csv')

In [105]:
df['hours']=df['runtime'].apply(lambda x: round((x/60),2)).astype(float) #runtime-i saata cevirib round edirik ve 
                                                                         #yeni column yaradiriq

In [106]:
df['hours']

0       0.80
1       1.88
2       1.52
3       1.57
4       2.22
        ... 
5801    1.67
5802    1.23
5803    1.47
5804    1.93
5805    0.00
Name: hours, Length: 5806, dtype: float64

### 5

In [ ]:
df['tmdb_score']=df['tmdb_score'].apply(lambda x: str(x).replace(',','.')).astype(float) #vergulleri noqte ile evez edib floata ceviririk

In [173]:
df.groupby('type').agg({'tmdb_score': ['min','max']})#type gore qruplasdirib tmdb_score-a uygun min, max valuelarini tapiriq

tmdb_score      
             min   max
type                  
MOVIE        1.0  65.0
SHOW         0.5  10.0

### 6

In [183]:
df.groupby(['type','release_year']).agg({'imdb_score': ['mean','min','max']}) #same, iki value gore qruplsdiriq

imdb_score          
                         mean  min  max
type  release_year                     
MOVIE 1953           6.800000  6.8  6.8
      1954           7.450000  7.4  7.5
      1956           6.700000  6.7  6.7
      1958           7.500000  7.5  7.5
      1959           6.700000  6.7  6.7
...                       ...  ...  ...
SHOW  2018           7.026923  3.4  9.6
      2019           7.009643  3.5  9.3
      2020           6.803600  2.5  9.1
      2021           6.747101  1.7  9.1
      2022           6.551087  1.6  9.2

[108 rows x 3 columns]

### 7

In [283]:
df.isna().sum()

id                         0
title                      1
type                       0
description               18
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score                 0
 imdb_votes              539
tmdb_popularity           94
tmdb_score                 0
dif                        0
dtype: int64

In [277]:
mean=round(df['tmdb_score'].mean(),1) 

In [263]:
nan_mask=df['tmdb_score'].isna() #nan olanlari boollean seklinde yaziriq

In [269]:
df.loc[nan_mask,'tmdb_score']=df.loc[nan_mask,'tmdb_score'].apply(lambda x: mean) #nan olan tmdb_scorelara mean apply edirik

In [276]:
df['tmdb_score']

0        6.8
1        8.2
2        7.8
3        7.8
4        7.7
        ... 
5801     6.8
5802     8.5
5803     6.8
5804     6.8
5805    10.0
Name: tmdb_score, Length: 5806, dtype: float64

In [307]:
df.loc[df['tmdb_popularity'].isna(),'tmdb_popularity']=df.loc[df['tmdb_popularity'].isna(),'tmdb_popularity'].apply(lambda x: 
                                                                                                round(df['tmdb_popularity'].mean(),3))

In [308]:
df['tmdb_popularity'] #same

0        0.600
1       27.612
2       18.216
3       17.505
4       95.337
         ...  
5801     0.966
5802     1.036
5803     0.709
5804     2.186
5805     0.979
Name: tmdb_popularity, Length: 5806, dtype: float64

In [274]:
df.loc[df['imdb_score'].isna(),'imdb_score']=df.loc[df['imdb_score'].isna(),'imdb_score'].apply(lambda x: 
                                                                                                round(df['imdb_score'].mean(),1))

In [275]:
df['imdb_score'] #same

0       6.5
1       8.3
2       8.2
3       8.0
4       8.1
       ... 
5801    6.9
5802    6.5
5803    6.5
5804    6.2
5805    8.8
Name: imdb_score, Length: 5806, dtype: float64

In [289]:
df['seasons'].mode(),df['seasons'].median() #mean yerine median ve ya mode ile evezlemek daha duzu=gun ola biler

(0    1.0
 Name: seasons, dtype: float64,
 1.0)

In [290]:
df.loc[df['seasons'].isna(),'seasons']=df.loc[df['seasons'].isna(),'seasons'].apply(lambda x: 1)

In [309]:
df.isna().sum()

id                         0
title                      1
type                       0
description               18
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                    0
imdb_id                  444
imdb_score                 0
 imdb_votes              539
tmdb_popularity            0
tmdb_score                 0
dif                        0
dtype: int64

### 8

In [236]:
df['genres']=df['genres'].map(eval) #stringin esl data type-na cevirir

In [242]:
df['genres'].apply(lambda x: len(x)).max() #arrayin maxiumum uzunluqunu tapir

9

### 9

In [281]:
mask=df['age_certification']=='R' # sertifikati 'R' olanlari boolean mask seklinde secir

In [282]:
df.loc[mask,'imdb_score'].min() #miniumum qiymetini tapir

2.1

### 10

In [279]:
df['dif']=abs(df['imdb_score'].apply(lambda x: x)-df['tmdb_score'].apply(lambda y: y)) #iki column ferqinin mutleq qiymetini tapir

In [280]:
df['dif'].max() # maxiumum ferqi tapir

59.7