In [1]:
import numpy as np

## Data Types


In [2]:
# numpy massivi 'int' data tipi ilə
saylar = np.array([1, 3, 2, 2, 2, 20, 2])
print('saylar', saylar.dtype)

saylar int32


In [3]:
# numpy massivi 'float' data tipi ilə
saylar = np.array([1, 3, 2, 2, 2, 20, 0.5])
print('saylar', saylar.dtype)

saylar float64


In [4]:
# numpy massivi 'unicode', a.k.a string data tipi ilə
mehsullar = np.array(['kolbasa','yağ','pendir','süd','çörək','yumurta','su'])
print('mehsullar', mehsullar.dtype)

mehsullar <U7


In [5]:
# numpy massivi qarışıq data tipləri ilə
kitablar = np.array([1984, 'Cinayət və Cəza', 'Zəfər Tağı'])
print(kitablar)
print(kitablar.dtype)

['1984' 'Cinayət və Cəza' 'Zəfər Tağı']
<U15


## Indexing

In [6]:
# mənfi olmayan rəqəmlərlə indekslənmə
for i in range(len(mehsullar)):
    print(f'mehsullar[{i}] -->', mehsullar[i])

mehsullar[0] --> kolbasa
mehsullar[1] --> yağ
mehsullar[2] --> pendir
mehsullar[3] --> süd
mehsullar[4] --> çörək
mehsullar[5] --> yumurta
mehsullar[6] --> su


In [7]:
# müsbət olmayan rəqəmlərlə indekslənmə
for i in range(-1,-(len(mehsullar)+1), -1):
    print(f'mehsullar[{i}] -->', mehsullar[i])

mehsullar[-1] --> su
mehsullar[-2] --> yumurta
mehsullar[-3] --> çörək
mehsullar[-4] --> süd
mehsullar[-5] --> pendir
mehsullar[-6] --> yağ
mehsullar[-7] --> kolbasa


In [8]:
# out of range indekslənmə
len(mehsullar)
mehsullar[8]

IndexError: index 8 is out of bounds for axis 0 with size 7

## Slicing

In [9]:
# massivin birinci elementindən sonuncu elementinə qədər hər elementi seçirik
mehsullar[0:7:1]

array(['kolbasa', 'yağ', 'pendir', 'süd', 'çörək', 'yumurta', 'su'],
      dtype='<U7')

In [10]:
mehsullar[::1]

array(['kolbasa', 'yağ', 'pendir', 'süd', 'çörək', 'yumurta', 'su'],
      dtype='<U7')

In [11]:
# massivin 1 indeksində yerləşən elementindən 6 indeksində 
# yerləşən elementinə qədər (6 daxil deyil!) hər ikinci elementi seçirik
mehsullar[1:6:2]

array(['yağ', 'süd', 'yumurta'], dtype='<U7')

In [12]:
# massivin başlanğıcından -4 indeksində yerləşən elementinə qədər hər elementi seçirik
mehsullar[0:-4]

array(['kolbasa', 'yağ', 'pendir'], dtype='<U7')

In [13]:
# massivin  -4 indeksində yerləşən elementindən -2 indeksində yerləşən elementinə 
# qədər (-2 daxil deyil) hər elementi seçirik
mehsullar[-4:-2]

array(['süd', 'çörək'], dtype='<U7')

## Broadcasting and operations

In [17]:
# siyahınızda olan məhsulları qeyd olunmuş sayda səbətə atırsınız
saylar = np.array([1, 3, 2, 2, 2, 20, 2])

In [23]:
# hər məhsuldan 1 ədəd də əlavə etmək istəyirsiniz
print(saylar + 1)

[ 2  4  3  3  3 21  3]


In [24]:
# səbət ağır oldu, hər məhsuldan 1 ədəd çıxmaq istəyirsiniz
print(saylar - 1)

[ 0  2  1  1  1 19  1]


In [25]:
# hər məhsula görə toplam qiyməti öyrənmək istəyirsiniz
qiymetler = np.array([7.99, 2.62, 3.99, 5.67, 0.50, 0.35, 2.5])
saylar = np.array([1, 3, 2, 2, 2, 20, 2])
mehsul_qiymetler = saylar * qiymetler
print(mehsullar)
print(mehsul_qiymetler)
print(sum(mehsul_qiymetler))

['kolbasa' 'yağ' 'pendir' 'süd' 'çörək' 'yumurta' 'su']
[ 7.99  7.86  7.98 11.34  1.    7.    5.  ]
48.17


In [26]:
# səbətin toplam qiymətini öyrənmək istəyirsiniz
qiymetler = np.array([7.99, 2.62, 3.99, 5.67, 0.50, 0.35, 2.5])
saylar = np.array([1, 3, 2, 2, 2, 20, 2])
toplam = np.dot(qiymetler,saylar)
print(toplam)

48.17


In [29]:
# qiymətlər 10% baxalaşdı və təzə toplam qiyməti hesablamaq istəyirsiniz
qiymetler = np.array([7.99, 2.62, 3.99, 5.67, 0.50, 0.35, 2.5])
saylar = np.array([1, 3, 2, 2, 2, 20, 2])
qiymetler = qiymetler * 1.1
toplam = np.dot(qiymetler,saylar)
print(toplam)

52.987


In [30]:
# ancaq süd məhsullarında qiymətlər 10% baxalaşdı və təzə toplam qiyməti hesablamaq istəyirsiniz
qiymetler = np.array([7.99, 2.62, 3.99, 5.67, 0.50, 0.35, 2.5])
saylar = np.array([1, 3, 2, 2, 2, 20, 2])
qiymetler[1:4] = qiymetler[1:4] * 1.1
print(qiymetler)
toplam = np.dot(qiymetler,saylar)
print(toplam)

[7.99  2.882 4.389 6.237 0.5   0.35  2.5  ]
50.888000000000005


In [31]:
# riyazi əməliyyatlar ancaq int və float data tipləri ilə keçərlidir
mehsullar * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U7'), dtype('int32')) -> None

## Funksiyalar

In [32]:
np.mean(qiymetler)

3.5497142857142854

In [33]:
np.median(qiymetler)

2.8820000000000006

In [34]:
np.max(qiymetler)

7.99

In [35]:
np.min(qiymetler)

0.35

In [36]:
np.isnan(qiymetler)

array([False, False, False, False, False, False, False])

In [38]:
np.std(qiymetler)

2.6384170965770752