In [2]:
!pip install numpy

You should consider upgrading via the 'C:\Users\u\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
saylar=np.array([1,2,3,4,5,6])

In [6]:
saylar

array([1, 2, 3, 4, 5, 6])

In [7]:
print(saylar.dtype)

int32


In [8]:
mehsullar=np.array(['anything','idk','okay'])

In [9]:
mehsullar.dtype

dtype('<U8')

In [10]:
kitablar=np.array(['1789','prences','anything'])

In [11]:
kitablar

array(['1789', 'prences', 'anything'], dtype='<U8')

In [15]:
kitablar[-1]

'anything'

In [22]:
kitablar[0:3:2]

array(['1789', 'anything'], dtype='<U8')

In [23]:
kitablar[0:-2]

array(['1789'], dtype='<U8')

In [25]:
kitablar[-3:-1]

array(['1789', 'prences'], dtype='<U8')

In [ ]:
broadcasting

In [26]:
saylar


array([1, 2, 3, 4, 5, 6])

In [21]:
saylar+1

array([2, 3, 4, 5, 6, 7])

In [31]:
x=np.array([1,2,3])
y=np.array([1,2,3])

In [32]:
x*y

array([1, 4, 9])

In [33]:
np.dot(x,y)

14

In [34]:
kitablar*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('int32')) -> None

In [35]:
np.mean(saylar)

3.5

In [36]:
np.median(saylar)

3.5

In [37]:
np.var(saylar)

2.9166666666666665

In [38]:
np.std(saylar)

1.707825127659933

In [40]:
np.min(saylar)

1

In [41]:
np.max(saylar)

6

In [44]:
saylar

array([1, 2, 3, 4, 5, 6])

In [45]:
!pip install pandas

You should consider upgrading via the 'C:\Users\u\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [46]:
import pandas as ps

In [49]:
df=ps.read_csv('tutorial9.csv')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770 entries, 0 to 769
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   number          770 non-null    int64 
 1   pokemon_name    770 non-null    object
 2   pic_url         770 non-null    object
 3   main_type       770 non-null    object
 4   secondary_type  376 non-null    object
 5   region          770 non-null    object
 6   category        770 non-null    object
 7   height          770 non-null    object
 8   weight          770 non-null    object
 9   pokemon_family  770 non-null    object
 10  attack          770 non-null    int64 
 11  defense         770 non-null    int64 
 12  stamina         770 non-null    int64 
 13  cp_range        770 non-null    object
 14  hp_range        770 non-null    object
 15  capture_rate    700 non-null    object
 16  flee_rate       700 non-null    object
 17  male_perc       611 non-null    object
 18  female_per

In [51]:
df.describe()

number      attack     defense     stamina
count  770.000000  770.000000  770.000000  770.000000
mean   387.740260  161.861039  142.588312  169.062338
std    226.559919   55.817370   50.171027   44.214794
min      1.000000   17.000000   32.000000    1.000000
25%    193.250000  118.000000  102.250000  137.000000
50%    385.500000  161.000000  139.000000  163.000000
75%    577.750000  204.000000  176.000000  190.000000
max    893.000000  345.000000  396.000000  496.000000

In [53]:
df.isna().sum()

number              0
pokemon_name        0
pic_url             0
main_type           0
secondary_type    394
region              0
category            0
height              0
weight              0
pokemon_family      0
attack              0
defense             0
stamina             0
cp_range            0
hp_range            0
capture_rate       70
flee_rate          70
male_perc         159
female_perc       159
resistance          8
weakness            8
wild_avail          0
egg_avail           0
raid_avail          0
research_avail      0
shiny               0
shadow              0
pkedex_desc         0
poss_attacks        0
dtype: int64

In [54]:
df['pokemon_name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...    
765     Runerigus
766       Falinks
767        Zacian
768     Zamazenta
769        Zarude
Name: pokemon_name, Length: 770, dtype: object

In [55]:
df.loc[0:10,'pokemon_name']

0      Bulbasaur
1        Ivysaur
2       Venusaur
3     Charmander
4     Charmeleon
5      Charizard
6       Squirtle
7      Wartortle
8      Blastoise
9       Caterpie
10       Metapod
Name: pokemon_name, dtype: object

In [56]:
df[['pokemon_name','category']]

pokemon_name   category
0      Bulbasaur       Seed
1        Ivysaur       Seed
2       Venusaur       Seed
3     Charmander     Lizard
4     Charmeleon      Flame
..           ...        ...
765    Runerigus     Grudge
766      Falinks  Formation
767       Zacian    Warrior
768    Zamazenta    Warrior
769       Zarude      Rogue

[770 rows x 2 columns]

In [ ]:
df.loc[]

In [58]:
df['pokemon_name']=='Charizard'

0      False
1      False
2      False
3      False
4      False
       ...  
765    False
766    False
767    False
768    False
769    False
Name: pokemon_name, Length: 770, dtype: bool

In [59]:
mask=df['pokemon_name']=='Charizard'

In [67]:
df.loc[1:5,'pokemon_name']

1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
Name: pokemon_name, dtype: object

In [69]:
##Data cleaning and wrangling

In [70]:
df.head()

number pokemon_name                                            pic_url  \
0       1    Bulbasaur  https://static.wikia.nocookie.net/pokemongo/im...   
1       2      Ivysaur  https://static.wikia.nocookie.net/pokemongo/im...   
2       3     Venusaur  https://static.wikia.nocookie.net/pokemongo/im...   
3       4   Charmander  https://static.wikia.nocookie.net/pokemongo/im...   
4       5   Charmeleon  https://static.wikia.nocookie.net/pokemongo/im...   

  main_type secondary_type region category height  weight     pokemon_family  \
0     Grass         Poison  Kanto     Seed  0.7 m  6.9 kg   Bulbasaur family   
1     Grass         Poison  Kanto     Seed    1 m   13 kg   Bulbasaur family   
2     Grass         Poison  Kanto     Seed    2 m  100 kg   Bulbasaur family   
3      Fire            NaN  Kanto   Lizard  0.6 m  8.5 kg  Charmander family   
4      Fire            NaN  Kanto    Flame  1.1 m   19 kg  Charmander family   

   ...                                         resistance  \
0  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
1  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
2  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
3  ...  {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...   
4  ...  {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...   

                                         weakness  wild_avail egg_avail  \
0  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
1  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
2  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
3           {'160%': ['Ground', 'Rock', 'Water']}        Yes         No   
4           {'160%': ['Ground', 'Rock', 'Water']}        Yes         No   

                   raid_avail research_avail shiny shadow  \
0  Formerly  (1st tier level)           Yes    Yes    Yes   
1  Formerly  (1st tier level)             No   Yes    Yes   
2  Formerly  (3rd tier level)      Formerly    Yes    Yes   
3  Formerly  (1st tier level)           Yes    Yes    Yes   
4  Formerly  (2nd tier level)      Formerly    Yes    Yes   

                                         pkedex_desc  \
0  Bulbasaur can be seen napping in bright sunlig...   
1  There is a bud on this Pokémon's back. To supp...   
2  Standard Pokédex description\nThere is a large...   
3  The flame that burns at the tip of its tail is...   
4  Charmeleon mercilessly destroys its foes using...   

                                        poss_attacks  
0  ['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo...  
1  ['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu...  
2  ['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ...  
3  ['Ember', 'Scratch', 'Flame Burst', 'Flame Cha...  
4  ['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'...  

[5 rows x 29 columns]

In [71]:
kg='6.9 kg'

In [72]:
type(kg)

str

In [76]:
kg.replace(' kg','')

'6.9'

In [77]:
kg=kg[:3]

In [80]:
kg=float(kg.split()[0])

In [92]:
df['weight']=df['weight'].apply(lambda x: float(x.split()[0]))

In [93]:
df['weight']

0        6.9
1       13.0
2      100.0
3        8.5
4       19.0
       ...  
765     66.6
766     62.0
767    110.0
768    210.0
769     70.0
Name: weight, Length: 770, dtype: float64

In [94]:
df['cp_range']

0      12-1,115
1      19-1,699
2      33-2,720
3        10-980
4      19-1,653
         ...   
765    27-2,273
766    28-2,357
767    47-3,829
768    47-3,829
769    47-3,833
Name: cp_range, Length: 770, dtype: object

In [96]:
df.head()

number pokemon_name                                            pic_url  \
0       1    Bulbasaur  https://static.wikia.nocookie.net/pokemongo/im...   
1       2      Ivysaur  https://static.wikia.nocookie.net/pokemongo/im...   
2       3     Venusaur  https://static.wikia.nocookie.net/pokemongo/im...   
3       4   Charmander  https://static.wikia.nocookie.net/pokemongo/im...   
4       5   Charmeleon  https://static.wikia.nocookie.net/pokemongo/im...   

  main_type secondary_type region category height  weight     pokemon_family  \
0     Grass         Poison  Kanto     Seed  0.7 m     6.9   Bulbasaur family   
1     Grass         Poison  Kanto     Seed    1 m    13.0   Bulbasaur family   
2     Grass         Poison  Kanto     Seed    2 m   100.0   Bulbasaur family   
3      Fire            NaN  Kanto   Lizard  0.6 m     8.5  Charmander family   
4      Fire            NaN  Kanto    Flame  1.1 m    19.0  Charmander family   

   ...                                         resistance  \
0  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
1  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
2  ...  {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...   
3  ...  {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...   
4  ...  {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...   

                                         weakness  wild_avail egg_avail  \
0  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
1  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
2  {'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}        Yes         No   
3           {'160%': ['Ground', 'Rock', 'Water']}        Yes         No   
4           {'160%': ['Ground', 'Rock', 'Water']}        Yes         No   

                   raid_avail research_avail shiny shadow  \
0  Formerly  (1st tier level)           Yes    Yes    Yes   
1  Formerly  (1st tier level)             No   Yes    Yes   
2  Formerly  (3rd tier level)      Formerly    Yes    Yes   
3  Formerly  (1st tier level)           Yes    Yes    Yes   
4  Formerly  (2nd tier level)      Formerly    Yes    Yes   

                                         pkedex_desc  \
0  Bulbasaur can be seen napping in bright sunlig...   
1  There is a bud on this Pokémon's back. To supp...   
2  Standard Pokédex description\nThere is a large...   
3  The flame that burns at the tip of its tail is...   
4  Charmeleon mercilessly destroys its foes using...   

                                        poss_attacks  
0  ['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo...  
1  ['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu...  
2  ['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ...  
3  ['Ember', 'Scratch', 'Flame Burst', 'Flame Cha...  
4  ['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'...  

[5 rows x 29 columns]

In [99]:
test1=df['resistance'][0]

In [100]:
test1


"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'Water'], '39%': ['Grass']}"

In [101]:
type(test1)

str

In [103]:
test1=eval(test1) #heyqi data tipini qaytarir

In [104]:
test1

{'62.5%': ['Electric', 'Fairy', 'Fighting', 'Water'], '39%': ['Grass']}

In [107]:
test1.keys()

dict_keys(['62.5%', '39%'])

In [120]:
list(test1.keys())

['62.5%', '39%']

In [122]:
for i in list(test1.keys()):
    i=i.replace('%','')
    i=float(i)
    

Grass 39
Grass 39


In [124]:
for key, value in test1.items():

    for cat in value:
        print(cat,key.replace('%',''))

Electric 62.5
Fairy 62.5
Fighting 62.5
Water 62.5
Grass 39


In [126]:
df.loc['resistance']=df.loc['resistance'].map(eval)

KeyError: 'resistance'

In [130]:
df.loc[~df['resistance'].isna(),'resistance']=df.loc[~df['resistance'].isna(),'resistance'].map(eval)

In [151]:
df.loc[~df['resistance'].isna(),'resistance'].apply(clean_column,colname='resistance').apply(ps.Series)

Electricresistance  Bugresistance  Fairyresistance  Fireresistance  \
0                  62.5            NaN              NaN             NaN   
1                  62.5            NaN              NaN             NaN   
2                  62.5            NaN              NaN             NaN   
3                   NaN           62.5              NaN             NaN   
4                   NaN           62.5              NaN             NaN   
..                  ...            ...              ...             ...   
765                 NaN           62.5              NaN             NaN   
766                 NaN           62.5              NaN             NaN   
767                 NaN           62.5              NaN             NaN   
768                 NaN           62.5              NaN             NaN   
769                 NaN            NaN              NaN             NaN   

     Fightingresistance  Ghostresistance  Poisonresistance  Waterresistance  \
0                   NaN              NaN               NaN              NaN   
1                   NaN              NaN               NaN              NaN   
2                   NaN              NaN               NaN              NaN   
3                   NaN              NaN               NaN              NaN   
4                   NaN              NaN               NaN              NaN   
..                  ...              ...               ...              ...   
765                 NaN              NaN               NaN              NaN   
766                 NaN              NaN               NaN              NaN   
767                 NaN              NaN               NaN              NaN   
768                 NaN              NaN               NaN              NaN   
769                 NaN              NaN               NaN              NaN   

     Psychicresistance  Iceresistance  Flyingresistance  Darkresistance  \
0                  NaN            NaN               NaN             NaN   
1                  NaN            NaN               NaN             NaN   
2                  NaN            NaN               NaN             NaN   
3                  NaN            NaN               NaN             NaN   
4                  NaN            NaN               NaN             NaN   
..                 ...            ...               ...             ...   
765                NaN            NaN               NaN             NaN   
766                NaN            NaN               NaN             NaN   
767                NaN            NaN               NaN             NaN   
768                NaN            NaN               NaN             NaN   
769                NaN            NaN               NaN            62.5   

     Grassresistance  Normalresistance  Dragonresistance  Steelresistance  \
0                NaN               NaN               NaN              NaN   
1                NaN               NaN               NaN              NaN   
2                NaN               NaN               NaN              NaN   
3                NaN               NaN               NaN              NaN   
4                NaN               NaN               NaN              NaN   
..               ...               ...               ...              ...   
765              NaN               NaN               NaN              NaN   
766              NaN               NaN               NaN              NaN   
767              NaN               NaN               NaN              NaN   
768              NaN               NaN               NaN              NaN   
769              NaN               NaN               NaN              NaN   

     Groundresistance  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN  
..                ...  
765               NaN  
766               NaN  
767               NaN  
768               NaN  
769               NaN  

[762 rows x 17 columns]

In [132]:
val_dict=dict()
for key,value in test1.items():
    print(key,value)
    for cat in value:
        val_dict[f'{cat} resistance']=float(key.replace('%',''))

62.5% ['Electric', 'Fairy', 'Fighting', 'Water']
39% ['Grass']


In [133]:
val_dict

{'Electric resistance': 62.5,
 'Fairy resistance': 62.5,
 'Fighting resistance': 62.5,
 'Water resistance': 62.5,
 'Grass resistance': 39.0}

In [148]:
def clean_column(row,colname):
    val_dict=dict()
    for key,value in row.items():
        for cat in value:
            val_dict[f'{cat}{colname}']=float(key.replace('%',''))
            return val_dict